export const optionsDemo1 = [
  {
    value: "江苏省",
    text: "江苏省",
    children: [
      {
        value: "南京市",
        text: "南京市",
        children: [
          { value: "玄武区", text: "玄武区" },
          { value: "秦淮区", text: "秦淮区" },
          { value: "建邺区", text: "建邺区" },
          { value: "鼓楼区", text: "鼓楼区" },
          { value: "浦口区", text: "浦口区" },
          { value: "栖霞区", text: "栖霞区" },
          { value: "雨花台区", text: "雨花台区" },
          { value: "江宁区", text: "江宁区" },
          { value: "六合区", text: "六合区" },
          { value: "溧水区", text: "溧水区" },
          { value: "高淳区", text: "高淳区" },
        ],
      },
      {
        value: "无锡市",
        text: "无锡市",
        children: [
          { value: "锡山区", text: "锡山区" },
          { value: "惠山区", text: "惠山区" },
          { value: "滨湖区", text: "滨湖区" },
          { value: "梁溪区", text: "梁溪区" },
          { value: "新吴区", text: "新吴区" },
          { value: "江阴市", text: "江阴市" },
          { value: "宜兴市", text: "宜兴市" },
        ],
      },
      {
        value: "徐州市",
        text: "徐州市",
        children: [
          { value: "鼓楼区", text: "鼓楼区" },
          { value: "云龙区", text: "云龙区" },
          { value: "贾汪区", text: "贾汪区" },
          { value: "泉山区", text: "泉山区" },
          { value: "铜山区", text: "铜山区" },
          { value: "丰县", text: "丰县" },
          { value: "沛县", text: "沛县" },
          { value: "睢宁县", text: "睢宁县" },
          { value: "新沂市", text: "新沂市" },
          { value: "邳州市", text: "邳州市" },
        ],
      },
      {
        value: "常州市",
        text: "常州市",
        children: [
          { value: "天宁区", text: "天宁区" },
          { value: "钟楼区", text: "钟楼区" },
          { value: "新北区", text: "新北区" },
          { value: "武进区", text: "武进区" },
          { value: "金坛区", text: "金坛区" },
          { value: "溧阳市", text: "溧阳市" },
        ],
      },
      {
        value: "苏州市",
        text: "苏州市",
        children: [
          { value: "虎丘区", text: "虎丘区" },
          { value: "吴中区", text: "吴中区" },
          { value: "相城区", text: "相城区" },
          { value: "姑苏区", text: "姑苏区" },
          { value: "吴江区", text: "吴江区" },
          { value: "常熟市", text: "常熟市" },
          { value: "张家港市", text: "张家港市" },
          { value: "昆山市", text: "昆山市" },
          { value: "太仓市", text: "太仓市" },
        ],
      },
      {
        value: "南通市",
        text: "南通市",
        children: [
          { value: "通州区", text: "通州区" },
          { value: "崇川区", text: "崇川区" },
          { value: "海门区", text: "海门区" },
          { value: "如东县", text: "如东县" },
          { value: "启东市", text: "启东市" },
          { value: "如皋市", text: "如皋市" },
          { value: "海安市", text: "海安市" },
        ],
      },
      {
        value: "连云港市",
        text: "连云港市",
        children: [
          { value: "连云区", text: "连云区" },
          { value: "海州区", text: "海州区" },
          { value: "赣榆区", text: "赣榆区" },
          { value: "东海县", text: "东海县" },
          { value: "灌云县", text: "灌云县" },
          { value: "灌南县", text: "灌南县" },
        ],
      },
      {
        value: "淮安市",
        text: "淮安市",
        children: [
          { value: "淮安区", text: "淮安区" },
          { value: "淮阴区", text: "淮阴区" },
          { value: "清江浦区", text: "清江浦区" },
          { value: "洪泽区", text: "洪泽区" },
          { value: "涟水县", text: "涟水县" },
          { value: "盱眙县", text: "盱眙县" },
          { value: "金湖县", text: "金湖县" },
        ],
      },
      {
        value: "盐城市",
        text: "盐城市",
        children: [
          { value: "亭湖区", text: "亭湖区" },
          { value: "盐都区", text: "盐都区" },
          { value: "大丰区", text: "大丰区" },
          { value: "响水县", text: "响水县" },
          { value: "滨海县", text: "滨海县" },
          { value: "阜宁县", text: "阜宁县" },
          { value: "射阳县", text: "射阳县" },
          { value: "建湖县", text: "建湖县" },
          { value: "东台市", text: "东台市" },
        ],
      },
      {
        value: "扬州市",
        text: "扬州市",
        children: [
          { value: "广陵区", text: "广陵区" },
          { value: "邗江区", text: "邗江区" },
          { value: "江都区", text: "江都区" },
          { value: "宝应县", text: "宝应县" },
          { value: "仪征市", text: "仪征市" },
          { value: "高邮市", text: "高邮市" },
        ],
      },
      {
        value: "镇江市",
        text: "镇江市",
        children: [
          { value: "京口区", text: "京口区" },
          { value: "润州区", text: "润州区" },
          { value: "丹徒区", text: "丹徒区" },
          { value: "丹阳市", text: "丹阳市" },
          { value: "扬中市", text: "扬中市" },
          { value: "句容市", text: "句容市" },
        ],
      },
      {
        value: "泰州市",
        text: "泰州市",
        children: [
          { value: "海陵区", text: "海陵区" },
          { value: "高港区", text: "高港区" },
          { value: "姜堰区", text: "姜堰区" },
          { value: "兴化市", text: "兴化市" },
          { value: "靖江市", text: "靖江市" },
          { value: "泰兴市", text: "泰兴市" },
        ],
      },
      {
        value: "宿迁市",
        text: "宿迁市",
        children: [
          { value: "宿城区", text: "宿城区" },
          { value: "宿豫区", text: "宿豫区" },
          { value: "沭阳县", text: "沭阳县" },
          { value: "泗阳县", text: "泗阳县" },
          { value: "泗洪县", text: "泗洪县" },
        ],
      },
    ],
  },
];
